#!/bin/bash
# Bu Arayüz Tamamen Bürküt Tarafın'dan Kodlanmıştır!
PROJECT_NAME=bürküt.sh
PROJECT_CREATER=$name
name=Bürküt
instagram=İnstagram:@burkut.sh
github=https://github.com/burkuts

echo 
"Herkese Merhaba Ben $name
Güncel Siber Güvenlik
Yazılımlarını Bir Araya Topladım

$instagram
$github"