#!/bin/bash

web_hacking() {
  echo "Bürküt Siber Güvenlik Yazılımına Hoşgeldiniz :) "
}

wi_fi_hacking() {
  echo "Some super cool code by John."
}

press_enter() {
  echo ""
  echo -n "	Press Enter to continue "
  read
  clear
}

incorrect_selection() {
  echo "Incorrect selection! Try again."
}

until [ "$selection" = "0" ]; do
  clear
  echo ""
  echo "    	1  -  Web Hacking"
  echo "    	2  -  Wi-Fi Hacking"
  echo "    	0  -  Exit"
  echo ""
  echo -n "  Enter selection: "
  read selection
  echo ""
  case $selection in
    1 ) clear ; web_hacking ; press_enter ;;
    2 ) clear ; wi_fi_hacking ; press_enter ;;
    0 ) clear ; exit ;;
    * ) clear ; incorrect_selection ; press_enter ;;
  esac
done